"""Friendly display names for tickers shown in the Mini App UI and other
user-facing surfaces.

Kept separate from src.collectors.news_data.SYMBOL_KEYWORDS (which is a
search-keyword map used for article→symbol matching). This one is
strictly "what shows up next to the ticker on screen."
"""

DISPLAY_NAMES: dict[str, str] = {
    # ---- Crypto ----
    'BTC': 'Bitcoin',
    'ETH': 'Ethereum',
    'SOL': 'Solana',
    'XRP': 'Ripple',
    'ADA': 'Cardano',
    'AVAX': 'Avalanche',
    'DOGE': 'Dogecoin',
    'MATIC': 'Polygon',
    'BNB': 'BNB',
    'TRX': 'TRON',
    'LINK': 'Chainlink',
    'DOT': 'Polkadot',
    'UNI': 'Uniswap',
    'ATOM': 'Cosmos',
    'NEAR': 'NEAR Protocol',
    'AAVE': 'Aave',
    'MKR': 'Maker',
    'HBAR': 'Hedera',
    'ICP': 'Internet Computer',
    'PEPE': 'Pepe',
    'SHIB': 'Shiba Inu',
    'TON': 'Toncoin',
    'SUI': 'Sui',
    'ARB': 'Arbitrum',
    'OP': 'Optimism',
    'LTC': 'Litecoin',
    'BCH': 'Bitcoin Cash',
    'XLM': 'Stellar',
    'ALGO': 'Algorand',
    'FIL': 'Filecoin',
    'VET': 'VeChain',
    'THETA': 'Theta',
    'SAND': 'The Sandbox',
    'MANA': 'Decentraland',
    'AXS': 'Axie Infinity',
    'IMX': 'Immutable',
    'GRT': 'The Graph',
    'EGLD': 'MultiversX',
    'FTM': 'Fantom',
    'INJ': 'Injective',
    'RUNE': 'THORChain',
    'CRV': 'Curve',
    'LDO': 'Lido',
    'ONDO': 'Ondo',
    'PYTH': 'Pyth Network',
    'ROSE': 'Oasis',
    'ZEC': 'Zcash',
    'XMR': 'Monero',

    # ---- US mega-cap tech ----
    'AAPL': 'Apple',
    'MSFT': 'Microsoft',
    'GOOGL': 'Alphabet',
    'GOOG': 'Alphabet',
    'AMZN': 'Amazon',
    'NVDA': 'Nvidia',
    'META': 'Meta Platforms',
    'TSLA': 'Tesla',
    'AVGO': 'Broadcom',
    'CRM': 'Salesforce',
    'ORCL': 'Oracle',
    'AMD': 'AMD',
    'ADBE': 'Adobe',
    'INTC': 'Intel',
    'QCOM': 'Qualcomm',
    'CSCO': 'Cisco',

    # ---- US financials ----
    'JPM': 'JPMorgan Chase',
    'BAC': 'Bank of America',
    'GS': 'Goldman Sachs',
    'MS': 'Morgan Stanley',
    'V': 'Visa',
    'MA': 'Mastercard',
    'BRK-B': 'Berkshire Hathaway',
    'BRK.B': 'Berkshire Hathaway',
    'WFC': 'Wells Fargo',
    'C': 'Citigroup',
    'BLK': 'BlackRock',
    'AXP': 'American Express',

    # ---- Healthcare ----
    'UNH': 'UnitedHealth',
    'JNJ': 'Johnson & Johnson',
    'LLY': 'Eli Lilly',
    'PFE': 'Pfizer',
    'ABBV': 'AbbVie',
    'MRK': 'Merck',
    'TMO': 'Thermo Fisher',
    'ABT': 'Abbott Labs',

    # ---- Energy ----
    'XOM': 'ExxonMobil',
    'CVX': 'Chevron',
    'COP': 'ConocoPhillips',
    'SLB': 'Schlumberger',
    'EOG': 'EOG Resources',
    'MPC': 'Marathon Petroleum',
    'VLO': 'Valero Energy',
    'HAL': 'Halliburton',
    'OXY': 'Occidental',
    'PSX': 'Phillips 66',
    'FRO': 'Frontline',
    'STNG': 'Scorpio Tankers',

    # ---- Consumer Discretionary ----
    'HD': 'Home Depot',
    'MCD': "McDonald's",
    'NKE': 'Nike',
    'SBUX': 'Starbucks',
    'UBER': 'Uber',
    'LYFT': 'Lyft',
    'RIVN': 'Rivian',
    'LCID': 'Lucid Motors',
    'F': 'Ford',
    'GM': 'General Motors',
    'ABNB': 'Airbnb',
    'BKNG': 'Booking Holdings',
    'MAR': 'Marriott',
    'DIS': 'Disney',

    # ---- Consumer Staples ----
    'WMT': 'Walmart',
    'COST': 'Costco',
    'KO': 'Coca-Cola',
    'PEP': 'PepsiCo',
    'PG': 'Procter & Gamble',
    'MO': 'Altria',

    # ---- Industrials ----
    'CAT': 'Caterpillar',
    'BA': 'Boeing',
    'GE': 'General Electric',
    'HON': 'Honeywell',
    'RTX': 'RTX',
    'LMT': 'Lockheed Martin',
    'NOC': 'Northrop Grumman',
    'GD': 'General Dynamics',
    'HII': 'Huntington Ingalls',
    'LHX': 'L3Harris',
    'TXT': 'Textron',
    'DE': 'Deere',
    'UPS': 'UPS',
    'FDX': 'FedEx',

    # ---- Communication ----
    'NFLX': 'Netflix',
    'CMCSA': 'Comcast',
    'T': 'AT&T',
    'VZ': 'Verizon',
    'WBD': 'Warner Bros. Discovery',

    # ---- Utilities / Power / Nuclear ----
    'NEE': 'NextEra Energy',
    'SO': 'Southern Company',
    'D': 'Dominion Energy',
    'VST': 'Vistra',
    'CEG': 'Constellation Energy',
    'OKLO': 'Oklo',
    'SMR': 'NuScale Power',
    'LEU': 'Centrus Energy',

    # ---- ETFs / Macro ----
    'SPY': 'S&P 500 ETF',
    'QQQ': 'Nasdaq 100 ETF',
    'IWM': 'Russell 2000 ETF',
    'DIA': 'Dow ETF',
    'GLD': 'Gold ETF',
    'SLV': 'Silver ETF',
    'USO': 'Oil ETF',
    'UNG': 'Natural Gas ETF',
    'URA': 'Uranium ETF',
    'COPX': 'Copper Miners ETF',
    'TLT': '20+ Year Treasury ETF',
    'HYG': 'High Yield Corp Bond ETF',
    'LQD': 'Inv. Grade Corp Bond ETF',
    'VIX': 'VIX',

    # ---- AI Pure-Play ----
    'AI': 'C3.ai',
    'BBAI': 'BigBear.ai',
    'UPST': 'Upstart',
    'PATH': 'UiPath',
    'SOUN': 'SoundHound AI',
    'SMCI': 'Super Micro Computer',
    'VRT': 'Vertiv',
    'DELL': 'Dell Technologies',
    'ARM': 'Arm Holdings',
    'ANET': 'Arista Networks',
    'MDB': 'MongoDB',
    'ESTC': 'Elastic',
    'CFLT': 'Confluent',
    'IONQ': 'IonQ',
    'RGTI': 'Rigetti Computing',
    'PLTR': 'Palantir',
    'SNOW': 'Snowflake',
    'NET': 'Cloudflare',
    'CRWD': 'CrowdStrike',
    'DDOG': 'Datadog',
    'ZS': 'Zscaler',
    'OKTA': 'Okta',

    # ---- European stocks ----
    'HSBA.L': 'HSBC',
    'BP.L': 'BP',
    'SHEL.L': 'Shell',
    'AZN.L': 'AstraZeneca',
    'GSK.L': 'GSK',
    'ULVR.L': 'Unilever',
    'RIO.L': 'Rio Tinto',
    'BARC.L': 'Barclays',
    'LLOY.L': 'Lloyds Banking',
    'LSEG.L': 'London Stock Exchange',
    'IHG.L': 'InterContinental Hotels',
    'AAL.L': 'Anglo American',
    'GLEN.L': 'Glencore',
    'FLTR.L': 'Flutter Entertainment',
    'SAP.DE': 'SAP',
    'SIE.DE': 'Siemens',
    'ALV.DE': 'Allianz',
    'MBG.DE': 'Mercedes-Benz',
    'BMW.DE': 'BMW',
    'BAS.DE': 'BASF',
    'DTE.DE': 'Deutsche Telekom',
    'BAYN.DE': 'Bayer',
    'ADS.DE': 'Adidas',
    'DBK.DE': 'Deutsche Bank',
    'TTE.PA': 'TotalEnergies',
    'AIR.PA': 'Airbus',
    'AI.PA': 'Air Liquide',
    'OR.PA': "L'Oréal",
    'MC.PA': 'LVMH',
    'SAN.PA': 'Sanofi',
    'BBVA.MC': 'BBVA',
    'SAN.MC': 'Santander',
    'IBE.MC': 'Iberdrola',
    'ENI.MI': 'Eni',
    'ISP.MI': 'Intesa Sanpaolo',
    'ENEL.MI': 'Enel',
    'STLA.MI': 'Stellantis',
    'AD.AS': 'Ahold Delhaize',
    'ASML.AS': 'ASML',
    'INGA.AS': 'ING Group',
    'NOVO-B.CO': 'Novo Nordisk',
    'MAERSK-B.CO': 'Maersk',
    'NESTE.HE': 'Neste',
    'UPM.HE': 'UPM',
    'EQNR.OL': 'Equinor',
    'DNB.OL': 'DNB Bank',
    'ROG.SW': 'Roche',
    'NESN.SW': 'Nestlé',
    'NOVN.SW': 'Novartis',

    # ---- Asia ----
    '1299.HK': 'AIA Group',
    '9988.HK': 'Alibaba',
    '700.HK': 'Tencent',
    '9618.HK': 'JD.com',
    '9999.HK': 'NetEase',
    '3690.HK': 'Meituan',
    '1211.HK': 'BYD',
    '0388.HK': 'Hong Kong Exchanges',
    '9984.T': 'SoftBank Group',
    '7203.T': 'Toyota',
    '6758.T': 'Sony',
    '8306.T': 'Mitsubishi UFJ',
    '9432.T': 'NTT',
    '6861.T': 'Keyence',
    '4063.T': 'Shin-Etsu Chemical',
    '7974.T': 'Nintendo',
    'RELIANCE.NS': 'Reliance Industries',
    'HDFCBANK.NS': 'HDFC Bank',
    'TCS.NS': 'Tata Consultancy',
    'INFY.NS': 'Infosys',
    'ICICIBANK.NS': 'ICICI Bank',
    'BHP.AX': 'BHP Group',
    'FMG.AX': 'Fortescue',
    'WDS.AX': 'Woodside Energy',
    'CBA.AX': 'Commonwealth Bank',

    # ---- Misc ----
    'SCHW': 'Charles Schwab',
    'PYPL': 'PayPal',
    'SQ': 'Block',
    'COIN': 'Coinbase',
    'MSTR': 'MicroStrategy',
    'HOOD': 'Robinhood',
}


def display_name(symbol: str) -> str | None:
    """Return a friendly display name for a ticker, or None if unknown."""
    if not symbol:
        return None
    return DISPLAY_NAMES.get(symbol)
